server:
  port : 9999
zuul:
  routes:
    offer:
      path: /offer/**
      url: http://65.2.132.251:1001/api/v1
    shoe:
      path: /shoe/**
      url: http://65.2.132.251:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://65.2.132.251:1003
    cart:
      path: /cart/**
      url: http://65.2.132.251:1004/api/v1
